spring: 
  datasource:
    url: jdbc:h2:file:./eventmanagement.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate # validate update create create-drop

event-magagement:
  users:
    - 
      username: dacapo
      password: "{bcrypt}$2a$10$Cf5rOfI9sqO7nnYKg8Y8JeeBvxn00X.TSYZw3VdP5OfZ6J0X6H3KC"
      roles:
        - USER
    -
      username: admin
      password: "{bcrypt}$2a$10$Cf5rOfI9sqO7nnYKg8Y8JeeBvxn00X.TSYZw3VdP5OfZ6J0X6H3KC"
      roles:
        - ADMIN