spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/dacapo"
    username: dacapo
    password: geheim
flyway:
  url: "jdbc:postgresql://localhost:5432/dacapo"
  schemas: public
  user: dacapo
  password: geheim
