spring:
  datasource:
    url: jdbc:h2:file:./eventmanagement.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

flyway:
  url: jdbc:h2:file:./eventmanagement.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC;
  schemas: public
  user: sa
  password: sa
